"""
Log-injection tests for web/oauth/middleware.py (#1146).

The middleware logs who authenticated with a bearer token. A newline in a logged
value must not reach the log as a line break, which would let a caller forge
entries. `scope` comes from the caller's authorization request; `client_id` is
generated by the server, but both are read back out of the token or the token
store, so both are wrapped.
"""

import logging

import pytest

from mcp_memory_service.web.oauth import middleware
from mcp_memory_service.web.oauth.authorization import create_access_token
from mcp_memory_service.web.oauth.middleware import authenticate_bearer_token
from mcp_memory_service.web.oauth.storage.memory import MemoryOAuthStorage

FORGED = "FORGED admin authenticated"
LOGGER = "mcp_memory_service.web.oauth.middleware"


def _messages(caplog):
    return [record.getMessage() for record in caplog.records]


@pytest.mark.asyncio
async def test_jwt_success_log_does_not_carry_newlines(caplog):
    token, _ = create_access_token("client-1", f"read\n{FORGED}")

    with caplog.at_level(logging.DEBUG, logger=LOGGER):
        result = await authenticate_bearer_token(token)

    assert result.authenticated
    messages = _messages(caplog)
    assert any("JWT authentication successful" in message for message in messages)
    for message in messages:
        assert f"\n{FORGED}" not in message
        assert token not in message


@pytest.mark.asyncio
async def test_stored_token_success_log_does_not_carry_newlines(caplog, monkeypatch):
    storage = MemoryOAuthStorage()
    token = "opaque-access-token"
    await storage.store_access_token(token, f"client-1\n{FORGED}", scope="read", expires_in=600)
    monkeypatch.setattr(middleware, "get_oauth_storage", lambda: storage)

    with caplog.at_level(logging.DEBUG, logger=LOGGER):
        result = await authenticate_bearer_token(token)

    assert result.authenticated
    messages = _messages(caplog)
    assert any("OAuth storage authentication successful" in message for message in messages)
    for message in messages:
        assert f"\n{FORGED}" not in message
        assert token not in message
